#
#  Go-lang-Vcs-NEXTClan 
#

package: verifier
output: openapi.gen.go
generate:
  models: true
  echo-server: true
  embedded-spec: false
import-mapping:
  ./common.yaml: github.com/trustbloc/vcs/pkg/restapi/v1/common
output-options:
  include-tags:
    - verifier
  exclude-schemas:
    - PresentationDefinition
